// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIlnUaEzjKqgZL-7-ImXviTKQM8kaaxZo',
    appId: '1:623616166591:web:020144ee8f0b1df621940a',
    messagingSenderId: '623616166591',
    projectId: 'wreckit-hackathon',
    authDomain: 'wreckit-hackathon.firebaseapp.com',
    storageBucket: 'wreckit-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCab2SJmKvfvVtmxz11ljg_d7gjRI9Z2eA',
    appId: '1:623616166591:android:08b4584101696ac121940a',
    messagingSenderId: '623616166591',
    projectId: 'wreckit-hackathon',
    storageBucket: 'wreckit-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1dTt54f2a7BvpWEp1C0lh2G1g7s3-AM8',
    appId: '1:623616166591:ios:c33b113fe5ec81ce21940a',
    messagingSenderId: '623616166591',
    projectId: 'wreckit-hackathon',
    storageBucket: 'wreckit-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.wreckit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1dTt54f2a7BvpWEp1C0lh2G1g7s3-AM8',
    appId: '1:623616166591:ios:c33b113fe5ec81ce21940a',
    messagingSenderId: '623616166591',
    projectId: 'wreckit-hackathon',
    storageBucket: 'wreckit-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.wreckit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIlnUaEzjKqgZL-7-ImXviTKQM8kaaxZo',
    appId: '1:623616166591:web:dff55317622bdae721940a',
    messagingSenderId: '623616166591',
    projectId: 'wreckit-hackathon',
    authDomain: 'wreckit-hackathon.firebaseapp.com',
    storageBucket: 'wreckit-hackathon.firebasestorage.app',
  );
}
